config/routes.rb
Rails.application.routes.draw do

# Home page
  root 'sessions#new'

# Resident

  # register new resident
  get 'sessions/new'
  get 'register', to: 'residents#new', as: 'register'
  post 'register', to: 'residents#create'

  # show all residents
  get 'residents/index', to: 'residents#index'

  # edit resident info
  get 'residents/:floor/:unit/edit', to: 'residents#edit'
  patch 'residents/:floor/:unit/edit', to: 'residents#update'

  # delete resident entry
  delete 'residents/:floor/:unit', to: 'residents#destroy'


# Sessions

  # login
  get 'login' , to: 'sessions#new'
  post 'login', to: 'sessions#create'

  #logout
  delete 'logout', to: 'sessions#destroy'


# Twilio
  post 'twilio', to: 'twilio#create'


# Visitor Pass
  resources :visitor_passes, only: [:new, :create]

# Visitor
  resources :visitors, only: [:new, :create, :edit, :update]


end

app/models/visitor.rb
class Visitor < ApplicationRecord
  validates :name,  presence: true
  validates :ic,    presence: true
  validates :phone, presence: true
  validates :email, presence: true
  validates :secret_key, presence: true

end

app/controllers/visitors_controller.rb
require 'pry'

class VisitorsController < ApplicationController

  def new
    # either resident or pass is wrong
    if !resident || !visitor_pass
      flash.now[:danger] = t('visitors.new.failure.invalid')
      render "home_pages/home"
      return
    end

    if visitor_pass.expired?
      flash.now[:danger] = t('visitors.new.failure.expired')
      render "home_pages/home"
      return
    end

    if !visitor_pass.active?
      flash.now[:danger] = t('visitors.new.failure.used')
      render "home_pages/home"
      return
    end

    @visitor = Visitor.new
    @visitor_pass = visitor_pass
    @resident = resident

  end

  def create
    @visitor = Visitor.new(visitor_params)
    @visitor_pass = VisitorPass.find_by(id: params['visitor_pass_id'])
    @resident = Resident.find_by(id: params['resident_id'])

    # verify the secret key submitted by the visitor
    if correct_secret_key? && @visitor.save

      send_qrcode

      @visitor_pass.update(active: false)

      flash.now[:success] = t('visitors.create.success')
      render 'home_pages/home'
    else
      unless correct_secret_key?
        @visitor.errors.delete :secret_key
        @visitor.errors.add(:secret_key,t('visitors.create.failure.secret_key'))
      end
      render 'new'
    end

  end



  private

      def resident
        Resident.find_by(id: params[:resident_id])
      end

      def visitor_pass
        VisitorPass.find_by( visitor_pass_params )
      end

      def visitor_pass_params
        params.permit(:token, :resident_id)
      end

      def visitor_params
        params.require(:visitor)
              .permit(:name,
                  :ic,
                  :phone,
                  :email,
                  :car,
                  :secret_key)
      end

      def path
        "#{Rails.root}/app/assets/images/qrcode#{visitor_pass.id}.png"
      end

      def correct_secret_key?
        @visitor.secret_key == @visitor_pass.secret_key
      end

      def send_qrcode
        qrcode_client = QrcodeClient.new
        qrcode_client.generate2(resident: @resident, visitor: @visitor, path: path)
        ResidentMailer.qrcode(@visitor, path).deliver_now

      end
end

app/helpers/visitors_helper.rb
module VisitorsHelper
end

app/views/visitors/new.html.erb
<% provide(:title, 'Visitor Registration') %>

<h1>Visitor Registration</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_for( @visitor, url: visitors_path ) do |f| %>

    <%= render partial: 'shared/error_messages', locals: { model: @visitor } %>

    <%= hidden_field_tag :resident_id, @resident.id %>
    <%= hidden_field_tag :visitor_pass_id, @visitor_pass.id %>

    <%= f.label :name, "name" %>
    <%= f.text_field :name, class: 'form-control' %>

    <%= f.label :ic, "ic" %>
    <%= f.text_field :ic, class: 'form-control' %>

    <%= f.label :phone, "phone no." %>
    <%= f.text_field :phone, class: 'form-control' %>

    <%= f.label :email %>
    <%= f.email_field :email, class: 'form-control' %>

    <%= f.label :car, "car no. ( optional )" %>
    <%= f.text_field :car, class: 'form-control' %>

    <%= f.label :secret_key, "Secret key" %>
    <%= f.text_field :secret_key, class: 'form-control' %>

    <%= f.submit "Register", class: "btn btn-primary" %>

  <% end %>

  </div>

</div>