config/routes.rb
Rails.application.routes.draw do

# Home page
  root 'sessions#new'

# Resident

  # register new resident
  get 'sessions/new'
  get 'register', to: 'residents#new', as: 'register'
  post 'register', to: 'residents#create'

  # show all residents
  get 'residents/index', to: 'residents#index'

  # edit resident info
  get 'residents/:floor/:unit/edit', to: 'residents#edit'
  patch 'residents/:floor/:unit/edit', to: 'residents#update'

  # delete resident entry
  delete 'residents/:floor/:unit', to: 'residents#destroy'


# Sessions

  # login
  get 'login' , to: 'sessions#new'
  post 'login', to: 'sessions#create'

  #logout
  delete 'logout', to: 'sessions#destroy'


# Twilio
  post 'twilio', to: 'twilio#create'


# Visitor Pass
  resources :visitor_passes, only: [:new, :create]

# Visitor
  resources :visitors, only: [:new, :create, :edit, :update]


end

app/controllers/visitor_passes_controller.rb
class VisitorPassesController < ApplicationController


  def new
    @visitor_pass = VisitorPass.new

    # this is needed for the link in the header
    @controller = "visitor_passes"
  end

  def create

    @visitor_pass = create_visitor_pass

    if invalid_resident_key?
      @visitor_pass.errors.slice!
      @visitor_pass.errors.add(:base, "Resident key is invalid")
      render 'new'
      return
    end

    if @visitor_pass.save
      # send email
      ResidentMailer.visitor_details(@visitor_pass).deliver_now
      flash.now[:success] = success_message
      render 'home_pages/home'
    else
      render 'new'
    end



    # unless @visitor_pass.save
    #   unless resident && correct_resident_key?
    #     @visitor_pass.errors.slice!
    #     @visitor_pass.errors.add(:base, "Resident key is invalid.")
    #   end
    #   render 'new'
    # else
    #   # send email
    #   # ResidentMailer.visitor_details(@visitor_pass).deliver_now
    #   flash.now[:success] = success_message
    #   render 'home_pages/home'
    # end


  end


  private

      def resident_params
        params.permit(:floor, :unit)
      end

      def resident
        Resident.find_by(resident_params)
      end

      def visitor_pass_params
        params.permit(  :visitors_name,
                        :visitors_email,
                        :secret_key )
      end

      def create_visitor_pass
        vs = VisitorPass.new(visitor_pass_params)
        vs.update(resident_id:      resident.id,
                    token:          generate_token,
                    created_at:     Time.zone.now )
        vs
      end

      def correct_resident_key?
        resident.authenticate(params[:resident_key])
      end

      def invalid_resident_key?
        resident && !resident.authenticate(params[:resident_key])
      end

      def generate_token
        SecureRandom.urlsafe_base64
      end

      def success_message
         "The email has been sent to the visitor. Thank you."
      end

      def failure_message
        msg = "Sorry. Something went wrong."
      end

end

app/helpers/visitor_pass_helper.rb
module VisitorPassHelper
end

app/views/visitor_passes/new.html.erb
<% provide(:title, 'Visitor Pass') %>

<h1>Visitor Pass</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">

  <%= form_with( url: visitor_passes_path, local: true ) do |f| %>

    <%= render partial: 'shared/error_messages', locals: { model: @visitor_pass } %>

    <%
       floors = 1.upto(10).to_a
       units = 1.upto(15).to_a
    %>

    <div class="form-group">
      <div class="drop-down">
        <div class='col-md-6'>
          <%= f.label :floor %>
          <%= f.select(:floor, options_for_select(floors)) %>
        </div>
        <div class='col-md-6'>
          <%= f.label :unit %>
          <%= f.select(:unit, options_for_select(units))%>
        </div>
      </div>
    </div>

    <%= f.label :resident_key, "Your Resident Key" %>
    <%= f.password_field :resident_key , class: 'form-control' %>

    <%= f.label :visitors_name, "Visitor's Name" %>
    <%= f.text_field :visitors_name, class: 'form-control' %>

    <%= f.label :visitors_email, "Visitor's Email" %>
    <%= f.email_field :visitors_email, class: 'form-control' %>

    <p>Please supply a secret key for this visitor. ( e.g. 12345, apple, malaysia. ) <br>
      The vistor will be asked at the guard house for verification.</p>

    <%= f.label :secret_key,  "Secret Key" %>
    <%= f.text_field :secret_key, class: 'form-control' %>

    <%= f.submit "Submit", class: "btn btn-primary" %>
  <% end %>
  </div>

</div>